[libraries]
# Android
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
android-material = "com.google.android.material:material:1.8.0"
androidx-constraint-layout = "androidx.constraintlayout:constraintlayout:2.1.4"

# Test
junit = "junit:junit:4.13.2"
test-ext-junit = "androidx.test.ext:junit:1.1.5"
expresso-core = "androidx.test.espresso:espresso-core:3.5.1"