name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SDK 1.17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Run Mockoon CLI
        uses: mockoon/cli-action@v1
        with:
          version: 'latest'
          data-file: './mockoon-server.json'
          port: 3000
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build debug
        run: ./gradlew --no-daemon testE2eDebugUnitTest

