name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SDK 1.17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setuop Android SDK
        uses: android-actions/setup-android@v2

#      - name: Unit test
#        run: ./gradlew coverAllVariants
#
#      - name: Merge report
#        run: ./gradlew allDebugCoverage

      - name: Build debug
        run: ./gradlew --no-daemon assembleDebug assembleDebugAndroidTest

      - name: Build debug
        run: ./gradlew --no-daemon assembleDebugAndroidTest


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.FIREBASE_AUTH }}'

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --results-bucket cloud-test-heroes-ef5c5 --project=heroes-ef5c5 --device model=Pixel2,version=28,locale=pl,orientation=portrait
#        gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Pixel2,version=28,locale=pl,orientation=portrait --project=heroes-ef5c5



#      - name: Run Instrumentation Tests in Firebase Test Lab Presentation Characters Module
#        run: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --test feature/character/presentation/build/outputs/apk/androidTest/debug/presentation-debug-androidTest.apk --device model=Pixel2,version=28,locale=pl,orientation=portrait
#
#      - name: Run Instrumentation Tests in Firebase Test Lab Ui Module
#        run: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --test  ui/components/build/outputs/apk/androidTest/debug/components-debug-androidTest.apk --device model=Pixel2,version=28,locale=pl,orientation=portrait
#

