name: CI
on:
  push:
    branches: [ "develop", "main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SDK 1.17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Unit test
        run: ./gradlew coverAllVariants

      - name: Merge report
        run: ./gradlew allDebugCoverage

      - name: Build debug
        run: ./gradlew --no-daemon assembleDebug
